library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp.views import *

admin.site.site_header = "Library Mamagement System"
admin.site.site_title = "Library Mamagement Admin Protal"
admin.site.index_title = "Welcome to Library Mamagement System"
urlpatterns = [
    path('', home, name='home'),
    path('user_login/', user_login, name='user_login'),
    path('dashboard/', dashboard, name='dashboard'),
    path('member_add/', member_add, name='member_add'),
    path('member_edit/<int:pid>', member_edit, name='member_edit'),
    path('member_delete/<int:pid>', member_delete, name='member_delete'),
    path('member_table/', member_table, name='member_table'),
    path('book_add/', book_add, name='book_add'),
    path('book_edit/<int:pid>', book_edit, name='book_edit'),
    path('book_delete/<int:pid>', book_delete, name='book_delete'),
    path('book_table/', book_table, name='book_table'),
    path('profile/', profile, name='profile'),
    path('issueBook/', issueBook, name='issueBook'),
    path('publisher_add/', publisher_add, name='publisher_add'),
    path('publisher_edit/<int:pid>', publisher_edit, name='publisher_edit'),
    path('publisher_table/', publisher_table, name='publisher_table'),
    path('publisher_delete/<int:pid>', publisher_delete, name='publisher_delete'),
    path('changePassword/', changePassword, name='changePassword'),
    path('search/', search, name='search'),
    path('search2/', search2, name='search2'),
    path('user_logout/', user_logout, name='user_logout'),
    path('viewRequestDetails/<int:pid>', viewRequestDetails, name='viewRequestDetails'),
]

myapp/models.py
from django.db import models


class Publisher(models.Model):
    pub_id = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Book(models.Model):
    book_id = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=100, null=True)
    author = models.CharField(max_length=100, null=True)
    price = models.CharField(max_length=10, null=True)
    available = models.CharField(max_length=20, null=True)
    publisher = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.title


class Member(models.Model):
    memb_id = models.CharField(max_length=20, null=True)
    name = models.CharField(max_length=50, null=True)
    memb_type = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=200, null=True)
    memb_date = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.memb_id


class Brrowe_by(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    book = models.OneToOneField(Book, on_delete=models.CASCADE, null=True)
    due_date = models.DateTimeField(null=True)
    return_date = models.DateTimeField(null=True)
    issue_date = models.DateTimeField(null=True)

    def __str__(self):
        return f"{self.member} + {self.book}"

myapp/forms.py
from django import forms
from .models import *


class BookForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ['book_id', 'title', 'author', 'price', 'available', 'publisher']
    labels = {'book_id':'book_id', 'title':'title', 'author':'author', 'price':'price', 'available':'available', 'publisher':'publisher'}
    widgets = {
        'book_id': forms.TextInput(attrs={'class': 'form-select form-control', 'placeholder': 'Enter Book ID'},),
        'title': forms.TextInput(attrs={'class': 'form-select form-control', 'placeholder': 'Enter Title'}),
        'author': forms.TextInput(attrs={'class': 'form-select form-control', 'placeholder': 'Enter Author'}),
        'price': forms.TextInput(attrs={'class': 'form-select form-control', 'placeholder': 'Enter Price'}),
        'available': forms.TextInput(attrs={'class': 'form-select form-control'}),
        'publisher': forms.TextInput(attrs={'class': 'form-select form-control'}),
    }

class Brrowe_byForm(forms.ModelForm):
  class Meta:
    model = Brrowe_by
    fields = ['member', 'book']

class PublisherForm(forms.ModelForm):
  class Meta:
    model = Publisher
    fields = ['pub_id','name', 'address']

myapp/views.py
import datetime
from django.db.models import Q
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from datetime import date, datetime
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


def home(request):
    if not request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        return redirect(dashboard)


def dashboard(request):
    if not request.user.is_authenticated:
        return redirect(user_login)
    
    total_book = Book.objects.all().count()
    total_member = Member.objects.all().count()
    return render(request, 'dashboard.html', locals())


def member_table(request):
    members = Member.objects.all()
    total_member = members.count()

    sd = None
    if request.method == 'POST':
        sd = request.POST['searchdata']
        try:
            memberSearch = Member.objects.filter(Q(memb_id=sd) | Q(name__icontains=sd) | Q(address__icontains=sd))
        except:
            memberSearch = ""

    return render(request, 'member_table.html', locals())


def member_add(request):
    if not request.user.is_authenticated:
        return redirect('user_login')
    error = ""
    if request.method == 'POST':
        memb_id = request.POST['memb_id']
        name = request.POST['name']
        memb_type = request.POST['memb_type']
        address = request.POST['address']
        # memb_date = request.POST['memb_date']
        # expiry_date = request.POST['expiry_date']

        try:
            Member.objects.create(memb_id=memb_id, name=name, memb_type=memb_type,address=address)
            error = "no"

        except Exception:
            error = "yes"
    return render(request, 'member_add.html', locals())

def member_edit(request, pid):
    if not request.user.is_authenticated:
        return redirect('user_login')
    member = Member.objects.get(id = pid)
    error = ""
    if request.method == "POST":
        name = request.POST['name']
        memb_type = request.POST['memb_type']
        address = request.POST['address']

        member.name = name
        member.memb_type = memb_type
        member.address = address

        try:
            member.save()
            error = "no"
        except:
            error = "yes"
    return render(request, 'member_edit.html', locals())

def member_delete(request,pid):
    if not request.user.is_authenticated:
        return redirect('user_login')
    member = Member.objects.get(id=pid)
    member.delete()
    return redirect('member_table')


def book_add(request):
    if not request.user.is_authenticated:
        return redirect('user_login')
    # error = ""
    publisher = Publisher.objects.all()
    book = BookForm(request.POST)
    if request.method == "POST":
        try:
            if book.is_valid():
                book.save()
                error = "no"
                book = BookForm()
        except:
            book = BookForm()
            error = 'yes'
   
    return render(request, 'book_add.html', locals())


def book_table(request):
    books = Book.objects.all()

    sd = None
    if request.method == 'POST':
        sd = request.POST['searchdata']
        try:
            bookSearch = Book.objects.filter(Q(book_id=sd) | Q(title__icontains=sd) | Q(author__icontains=sd) | Q(publisher__icontains=sd))
        except:
            bookSearch = ""
    return render(request, 'book_table.html', locals())

def book_edit(request, pid):
    if not request.user.is_authenticated:
        return redirect('user_login')
    book = Book.objects.get(id = pid)
    publisher = Publisher.objects.all()
    error = ""
    if request.method == "POST":
        book_id = request.POST['book_id']
        title = request.POST['title']
        author = request.POST['author']
        price = request.POST['price']
        available = request.POST['available']
        publisher = request.POST['publisher']

        book.book_id = book_id
        book.title = title
        book.author = author
        book.price = price
        book.available = available
        book.publisher = publisher


        try:
            book.save()
            error = "no"
        except:
            error = "yes"
    return render(request, 'book_edit.html', locals())

def book_delete(request,pid):
    if not request.user.is_authenticated:
        return redirect('user_login')
    book = Book.objects.get(id=pid)
    book.delete()
    return redirect('book_table')

def profile(request):
    pass
    # return render(request, 'profile.html')



def issueBook(request):
    if not request.user.is_authenticated:
        return redirect('user_login')

    form = Brrowe_byForm(request.POST)

    if request.method == "POST":
        try:
            if form.is_valid():
                form.save()
                error = "no"
                form = Brrowe_byForm()
        except:
            form = Brrowe_byForm()
            error = 'yes'


    books = Book.objects.all()
    return render(request, 'issueBook.html', locals())


def viewRequestDetails(request, pid):
    if not request.user.is_authenticated:
        return redirect('user_login')

    form = Brrowe_byForm(request.POST)
    if request.method == "POST":
        try:
            if form.is_valid():
                form.save()
                error = "no"
                form = Brrowe_byForm()
        except:
            form = Brrowe_byForm()
            error = 'yes'

    member = Member.objects.get(id=pid)
    issue = Brrowe_by.objects.filter(member=member)
    issue_count = issue.count()
    return render(request, 'viewRequestDetails.html', locals())



def user_login(request):
    if not request.user.is_authenticated:
        error = ""
        if request.method == 'POST':
            u = request.POST['uname']
            p = request.POST['password']
            user = authenticate(username=u, password=p)
            try:
                if user.is_staff:
                    login(request, user)
                    error = "no"
                else:
                    error = "yes"
            except Exception:
                error = "yes"
        return render(request, 'login.html', locals())
    else:
        return redirect('dashboard')


def changePassword(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    error = ""
    user = request.user
    if request.method == "POST":
        o = request.POST['oldpassword']
        n = request.POST['newpassword']
        try:
            u = User.objects.get(id=request.user.id)
            if user.check_password(o):
                u.set_password(n)
                u.save()
                error = "no"
            else:
                error = 'not'
        except:
            error = "yes"
    return render(request, 'admin/changePassword.html', locals())


def search(request):
    if not request.user.is_authenticated:
        return redirect('user_login')
    sd = None
    if request.method == 'POST':
        sd = request.POST['searchdata']
        try:
            member = Member.objects.filter(Q(name__icontains=sd) | Q(memb_id=sd) | Q(address__icontains=sd))
        except:
            member = ""
    return render(request, 'search.html', locals())


def search2(request):
    if not request.user.is_authenticated:
        return redirect('user_login')
    sd = None
    if request.method == 'POST':
        sd = request.POST['searchdata']
        try:
            member = Member.objects.filter(Q(name__icontains=sd) | Q(memb_id=sd) | Q(address__icontains=sd))
        except:
            member = ""
    return render(request, 'search2.html', locals())


def user_logout(request):
    logout(request)
    return redirect(home)
    # return render(request, 'login.html')


def publisher_add(request):
    publisher = PublisherForm(request.POST)
    if request.method == 'POST':
        try:
            if publisher.is_valid():
                pub_id = request.POST['pub_id']
                name = request.POST['name']
                address = request.POST['address']
                pub = Publisher(pub_id=pub_id, name=name, address=address)
                pub.save()
                error = "no"
                publisher = PublisherForm()
        except:
            publisher = PublisherForm()
            error = 'yes'
    return render(request, 'publisher_add.html', locals())


def publisher_edit(request, pid):
    publisher = Publisher.objects.get(id=pid)
    error = ""
    if request.method == "POST":
        pub_id = request.POST['pub_id']
        name = request.POST['name']
        address = request.POST['address']

        publisher.pub_id = pub_id
        publisher.name = name
        publisher.address = address

        try:
            publisher.save()
            error = "no"
        except:
            error = "yes"
    return render(request, 'publisher_edit.html', locals())


def publisher_table(request):
    publishers = Publisher.objects.all()
    sd = None
    if request.method == 'POST':
        sd = request.POST['searchdata']
        try:
            pubSearch = Publisher.objects.filter(Q(pub_id=sd) | Q(name__icontains=sd) | Q(address__icontains=sd))
        except:
            pubSearch = ""
    return render(request, 'publisher_table.html', locals())


def publisher_delete(request, pid):
    if not request.user.is_authenticated:
        return redirect('user_login')
    publisher = Publisher.objects.get(id=pid)
    publisher.delete()
    return redirect('publisher_table')

myapp/templates/book_table.html
{% extends 'dashboard.html' %}
{% load static %}


{% block main %}
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
          <h1 class="h3 mb-0 text-gray-800">Book Detail</h1>
                
          <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
              <!-- <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">
              <button class="btn btn-outline-secondary" type="button" id="button-addon2">Button</button> -->  
              <input type="text" name="searchdata" class="form-control" placeholder="Enter Book ID/Title/Author / Publisher" required>
              <input type="submit" value="Search" class="btn btn-primary">
            </div>
          </form>
          <a href="{% url 'book_add' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus-circle fa-sm text-white-100"></i>
            Add New Book
          </a>
        </div>          

        <div class="row mt-2 rounded shadow mx-2 bg-white">
          <div class="col">
            {% if bookSearch %}
              <div class="card-body">
                <table id="example1" class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width:8%;">Book ID</th>
                      <th style="width:25%;">Title</th>
                      <th style="width:25%;">Author</th>
                      <th style="width:3%;" >Price</th>
                      <th style="width:8%;">Available</th>
                      <th style="width:15%;">Publisher</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in bookSearch %}
                      <tr>
                        <td>{{i.book_id}}</td>
                        <td>{{i.title}}</td>
                        <td>{{i.author}}</td>
                        <td>{{i.price}}</td>
                        <td>{{i.available}}</td>
                        <td>{{i.publisher}}</td>
                        <td>
                          <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'book_edit' i.id %}">
                                <i class="fa fa-edit"></i></a> &nbsp;&nbsp;&nbsp;
                            {% if perms.myapp.delete_book %}
                            <a class="btn btn-danger" onclick="return confirm('Are you sure to Delete ?')" href="{% url 'book_delete' i.id %}">
                                <i class="fa fa-trash-alt"></i>
                            </a>
                            {% endif %}
                          </div>
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            {% else %} 
            <div class="card-body">
              <table id="example1" class="table table-bordered ">
                <thead>
                  <tr>
                    <th style="width:8%;">Book ID</th>
                    <th style="width:25%;">Title</th>
                    <th style="width:25%;">Author</th>
                    <th style="width:3%;" >Price</th>
                    <th style="width:8%;">Available</th>
                    <th style="width:15%;">Publisher</th>
                    <th>Action</th>
                  </tr>
                </thead>

                <tbody>
                  {% for i in books %}
                    <tr>
                      <td>{{i.book_id}}</td>
                      <td>{{i.title}}</td>
                      <td>{{i.author}}</td>
                      <td>{{i.price}}</td>
                      <td>{{i.available}}</td>
                      <td>{{i.publisher}}</td>
                      <td>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'book_edit' i.id %}">
                                <i class="fa fa-edit"></i></a> &nbsp;&nbsp;&nbsp;
                            {% if perms.myapp.delete_book %}
                                <a class="btn btn-danger" onclick="return confirm('Are you sure to Delete ?')" href="{% url 'book_delete' i.id %}">
                                <i class="fa fa-trash-alt"></i>
                            </a>
                            {% endif %}
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>




              {% comment %} <table class="table">
                <thead>
                  <tr>
                    <th>Book ID</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Price</th>
                    <th>Available</th>
                    <th>Publisher</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for book in books %}
                    <tr>
                      <td>{{book.book_id}}</a></td>
                      <td>{{book.title}}</td>
                      <td>{{book.author}}</td>
                      <td>{{book.price}}</td>
                      <td>{{book.available}}</td>
                      <td>{{book.publisher}}</td>
                      <td>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'book_edit' book.id %}">
                                <i class="fa fa-edit"></i></a> &nbsp;&nbsp;&nbsp;
                            <a class="btn btn-danger" onclick="return confirm('Are you sure to Delete ?')" href="{% url 'book_delete' book.id %}">
                                <i class="fa fa-trash-alt"></i>
                            </a>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table> {% endcomment %}
            {% endif %}
        </div>
      </div>
    </div>
  </div>
            
{% endblock main %}
    

            

myapp/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../static/bootstrap.min.css" />
	<link rel="stylesheet" href="../static/style.css" />
	<title>Document</title>
</head>
<body>
	<div class="container h-75">
		<div style="width:100%; margin-top: 3em;">
			<div class="alert alert-success">message</div>
				<form action="/books/search" method="GET">
		  			<div class="form-group">
		    			<div style="width: 100%">
		    				<div style="width: 90%; display: inline-block;">
		    					<input type="search" name="keyword" autofocus class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="" placeholder="Search for books...">
		    				</div>
							<button type="submit" style="margin-left: 5px;" class="btn btn-primary">Search</button>
		    			</div>
		  			</div>
				</form>
			</div>
			<div style="width:100%; margin-top: 3em;">
				<h4>Search Found</h4>
				<div class="card book">
			  		<img src="../static/images/bg.jpg" class="card-img-top" alt="{{book[1]}}">
			  		<div class="card-body">
			    		<h5 class="card-title"><a href="/books/{{book['id']}}">{{book['name']}}</a></h5>
			    			<span class="badge badge-warning" style="margin-bottom: 5px;">Assigned</span>
			    			<p class="card-text bookdesc">{{book['desc']}}</p>
						    <p class="card-text">
						    	<span class="badge badge-{{ 'primary' if book['count'] > 0 else 'secondary' }}" style="margin-bottom: 5px;"></span>
							</p>
			    		<a href="/books/add/{{book['id']}}" class="btn btn-outline-warning {{ 'disabled' if str(book['id']) in user_books else '' }}"><i class="bi bi-journal-plus"></i> message</a>
				  	</div>
				</div>
				<h4>No Books Found!</h4>
				<p>Please contact the librarian</p>
			</div>
		</div>
	</div>
</body>
</html>


	

myapp/templates/issueBook.html
{% extends 'dashboard.html' %} {% load static %} 

{% block main %}
<style>
  .form-select, #id_member, #id_book {
    display: block;
    width: 100%;
    padding: 0.375rem 2.25rem 0.375rem 0.75rem;
    -moz-padding-start: calc(0.75rem - 3px);
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e");
    background-repeat: no-repeat;
    background-position: right 0.75rem center;
    background-size: 16px 12px;
    border: 1px solid #ced4da;
    border-radius: 0.375rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }
  @media (prefers-reduced-motion: reduce) {
    .form-select, #id_member, #id_book {
      transition: none;
    }
  }
  .form-select:focus, #id_member:focus, #id_book:focus {
    border-color: #86b7fe;
    outline: 0;
    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
  }
  .form-select[multiple], .form-select[size]:not([size="1"]) {
    padding-right: 0.75rem;
    background-image: none;
  }
  .form-select:disabled, #id_member:disabled, #id_book:disabled {
    background-color: #e9ecef;
  }
  .form-select:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #212529;
  }
  
  .form-select-sm, {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
    padding-left: 0.5rem;
    font-size: 0.875rem;
    border-radius: 0.25rem;
  }
  
  .form-select-lg {
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
    padding-left: 1rem;
    font-size: 1.25rem;
    border-radius: 0.5rem;
  }
</style>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4" >
        <h1 class="h3 mb-0 text-gray-800">Issue/ Return Book</h1>        
      </div>

      <div class="row mt-2 rounded shadow mx-2 bg-white">
        <div class="col-6 m-auto p-4">
          <div class="card-body">
            <form action="" method="post">
              {% csrf_token %}
              <div class="my-3">
                <label for="memb_id" class="form-label">Member</label>
                {{form.member}}
                {{form.member.errors}}
              
                <label for="">Book</label>
                {{form.book}}
                {{form.book.errors}}
              <input type="submit" value="Submit">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock main %}
</div>
<script>

  {% if error == "no" %}
  <script>
    alert('Logged In Successfully');
    window.location=('{% url 'dashboard' %}');
  </script>
  {% endif %}
  
    {% if error == "yes" %}
    <script>
      alert('Invalid Credentials, Please try again');
    </script>
    {% endif %}
  </script>

myapp/templates/publisher_add.html
{% extends 'dashboard.html' %}
{% load static %}
  <style>
    #id_publisher {
      display: block;
      width: 100%;
      padding: 0.375rem 2.25rem 0.375rem 0.75rem;
      -moz-padding-start: calc(0.75rem - 3px);
      font-size: 1rem;
      font-weight: 400;
      line-height: 1.5;
      color: #212529;
      background-color: #fff;
      background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e");
      background-repeat: no-repeat;
      background-position: right 0.75rem center;
      background-size: 16px 12px;
      border: 1px solid #ced4da;
      border-radius: 0.375rem;
      transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
    }
    @media (prefers-reduced-motion: reduce) {
      #id_publisher {
        transition: none;
      }
    }
    #id_publisher:focus {
      border-color: #86b7fe;
      outline: 0;
      box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
    }
    #id_publisher[multiple], #id_publisher[size]:not([size="1"]) {
      padding-right: 0.75rem;
      background-image: none;
    }
    #id_publisher:disabled {
      background-color: #e9ecef;
    }
    #id_publisher:-moz-focusring {
      color: transparent;
      text-shadow: 0 0 0 #212529;
    }
    
    #id_publisher-sm {
      padding-top: 0.25rem;
      padding-bottom: 0.25rem;
      padding-left: 0.5rem;
      font-size: 0.875rem;
      border-radius: 0.25rem;
    }
    
    #id_publisher-lg {
      padding-top: 0.5rem;
      padding-bottom: 0.5rem;
      padding-left: 1rem;
      font-size: 1.25rem;
      border-radius: 0.5rem;
    }
  </style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
{% block main %}
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
        <div class="container-fluid">
            <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
                <h1 class="h3 mb-0 text-gray-800">Publisher Add</h1>
                {% comment %} 
                  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                      <i class="fas fa-download fa-sm text-white-50"></i>
                      Add New Member
                  </a> 
                {% endcomment %}
            </div>          

            <div class="row mt-2 rounded shadow mx-2 bg-white ">
                <div class="col-6 m-auto p-4">
                  <form method="post"> {% csrf_token %}
                    
                    <div class="my-3">
                      <label for="pub_id" class="form-label">Publisher ID</label>
                      <input type="text" class="form-control" id="pub_id" name="pub_id">
                    </div>
                    <div class="my-3">
                      <label for="name" class="form-label">Title</label>
                      <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="my-3">
                      <label for="address" class="form-label">Author</label>
                      <input type="text" class="form-control" id="address" name="address">
                    </div>
                    
                    <div class=" text-center">
                      <input type="submit" value="Add" class="col-4 btn btn-primary"> 
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
  
    {% if error == "no" %}
      <script>
              alert('New book has been created.');
              window.location=('{% url 'book_table' %}');
      </script>
    {% endif %}

    {% if error == "yes" %}
      <script>
              alert('Something went wrong, Try Again...');
      </script>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

{% endblock main %}
    